### ISSUE TITLE
[Feature Request] Auto save after day end

### ISSUE THREAD

**Issue by Scoooom** [Aragami-delp/PlateUp_Mods#2]
Right now it appears I must resave a run before I start a new one. This isn't the biggest issue, but was wondering if there was a way to autosave a run after a day is completed

**Comment by Aragami-delp** [comment]
So you mean to save a run, after each day completes? The game does that automatically. Before starting another one you can save the current.

Or do you mean a system that makes a backup of the current run in case you start a new one?

Or making a new save file after each day (and overriding the old)?

Autosave isnt't the biggest priority, but i'll add that to the ideas.

**Comment by Scoooom** [comment]
So, lets say I make a save on Pizza Prep Day 2. Lets call it save 01/01/1969 00:00:00 (EPOC)
I then continue to play.

Now, my friends want to play. Sweet! So I make a new run. 

Now it's the next day and I want to go back to my solo. If I load the save, it will be Prep Day 2. I tested this, but maybe I did something wrong?

EDIT: Just to clarify, this can be prevented by saving your run BEFORE creating a new run. But it would be nice if I didn't have to do that, and when a day ended it saved and overwrote the old save. I admit this would be a QOL update

**Comment by alterNERDtive** [comment]
In a similar vein, I had expected more like a “save slot” system; where you name a slot (e.g. “solo” for solo runs), and then the mod keeps the save file for that around in that slot. Now you want to host multiplayer and create a new slot. The latest state of the “solo” slot is saved for returning to it later.

So more like different profiles than a classic “save” system. I might fork this at some point if that’s OK :)

**Comment by Aragami-delp** [comment]
Now it saves after each day. But only if you have already made a save for that run before.
v1.3.3
