### ISSUE TITLE
[Feature Request] Option to delete saves

### ISSUE THREAD

**Issue by Scoooom** [Aragami-delp/PlateUp_Mods#3]
Right now as I see it, if I play a lot with this mod installed and have many different multiplayer or solo runs, the save menu will get very cluttered.

I would like to see the ability to delete saves, as well as for a save to be auto deleted after a run is failed. This prevents this mod from being a cheat utility, which I don't think this mod needs to do.

**Comment by Aragami-delp** [comment]
Deleting saves is on the todo list, and shouldn't take long to implement. But i first want to make sure, the core mod works.
For now you can manually delete saves by deleting the corresponding folder in "C:\Users\YourName\AppData\LocalLow\It's Happening\PlateUp\SaveSystem".

**Comment by Aragami-delp** [comment]
As for automatic deletion, I'll add that to the ideas list.
