### ISSUE TITLE
Abandon game overwrites saves

### ISSUE THREAD

**Issue by BatmanMCX** [Aragami-delp/PlateUp_Mods#4]
When starting a new game while a save is loaded and then abandoning the game ALL saves are overwritten.

Steps to reproduce:
0. Backup all saves
1. Have a previous game saved, named, and loaded
2. Start a new restaurant (pick layout and recipe)
3. Abandon game right away
4. Select and load any previous save from Save System
5. Use recover save, you will be in the abandoned restaurant

**Comment by Aragami-delp** [comment]
fixed in v1.3.3
